def get_enrichment_map():
    return {
        0: "java python c++ javascript typescript node react angular vue compilation exception syntax loop error debugger stacktrace variables functions compiler runtime bug glitch segfault null pointer memory leak threading async await concurrency deadlock git repository branch merge conflict pull request ide intellij eclipse vscode sdk framework middleware backend frontend fullstack rest graphql grpc websocket bash shell powershell command line script module package dependency npm pip maven gradle spring boot django flask express linux unix windows macos array dictionary hashmap linked list tree graph sort search algorithm",
        1: "excel forecast kpi trend ab testing cohort quantitative visual tableau powerbi statistical variance metric analytics dashboard pivot table vlookup hlookup macro vba pandas numpy scipy scikit-learn r matplotlib seaborn d3 chart graph scatter bar pie histogram regression correlation standard deviation mean median mode hypothesis null alternative sampling survey nps csat retention churn ltv cac funnel conversion attribution google analytics mixpanel amplitude segment datadog new relic splunk",
        2: "email response draft follow-up tone clarify leadership summarize meeting notes memo announcement presentation pitch proposal report executive summary update status newsletter press release speech talking points faq q&a interview script blog article post caption tweet social media copy copywrite proofread edit grammar spelling punctuation style format structure outline brainstorm thesis argument persuasion negotiation compromise agreement contract nda msa sow terms conditions policy procedure guideline manual handbook",
        3: "policy audit regulatory privacy sox aml compliance risk gap documentation scenario governance framework standard regulation law act statute directive mandate requirement rule guideline iso nist gdpr ccpa hipaa pci dss soc fedramp fisma glba sarbanes oxley anti money laundering kyc cdd edd sanctions ofac fcipa bribery corruption fraud embezzlement insider trading conflict of interest ethics whistleblower investigation internal external finding recommendation remediation mitigation control preventative detective corrective testing assessment evaluation review",
        4: "swot tradeoff roadmap roi portfolio scenario business case long-term organizational cost-benefit strategy vision mission goal objective okr balanced scorecard pestle porters five forces value chain core competency competitive advantage differentiation cost leadership focus blue ocean disruption innovation transformation change management merger acquisition joint venture partnership alliance outsourcing offshoring restructuring reorganization downsizing synergy economies of scale",
        5: "sop step-by-step workflow bottleneck escalation sla raci ticket triage checklist process operation procedure task activity instruction manual playbook standard operating procedure service level agreement key performance indicator metrics dashboard reporting tracking monitoring measuring continuous improvement lean six sigma kaizen 5s value stream mapping root cause analysis fishbone ishikawa 5 whys pareto control chart kanban agile scrum sprint backlog user story epic feature defect issue incident problem change request release deployment",
        6: "slide deck powerpoint whitepaper biography template summary condense briefing presentation pitch proposal report executive summary update newsletter press release speech talking points faq script blog article post caption copy proofread edit grammar spelling punctuation format structure outline brainstorm thesis visual graphic chart diagram image video audio multimedia interactive infographic",
        7: "explain definition overview simplify conceptual fundamentals clarify tutorial guide lesson course training education learning understanding comprehension concept theory principle model framework methodology approach strategy tactic technique tool system process phenomenon mechanism cause effect relationship connection implication consequence outcome result impact significance importance relevance meaning purpose objective goal aim",
        8: "llm chatgpt prompt generative ai artificial intelligence machine learning automation productivity bot chatbot virtual assistant rpa robotic process automation script macro zapier integromat power automate cognitive predictive prescriptive descriptive analytics data science deep learning neural network nlp natural language processing computer vision image recognition speech text translation sentiment analysis clustering classification regression anomaly detection",
        9: "brainstorm translate rephrase grammar wording organize checklist calendar schedule appointment meeting agenda minutes notes task to-do reminder alarm timer calculator converter dictionary thesaurus encyclopedia search query find locate track status progress report log journal diary spreadsheet document presentation slide image video audio file folder directory drive cloud sync backup restore",
        10: "aws ec2 s3 kubernetes docker k8s terraform load balancer dns vpc network infra cloud azure gcp google cloud vmware hyper-v virtual machine container pod cluster node deployment service ingress egress firewall router switch subnet ip mac port protocol tcp udp http https ssh ftp sftp smtp ssl tls certificate key pem rsa encryption decryption cipher",
        11: "budget expense revenue profit margin tax roi pricing break-even depreciation cash flow income statement balance sheet asset liability equity capital debt loan interest principal rate yield return investment portfolio stock bond mutual fund etf option derivative commodity currency forex exchange spread bid ask volume market capitalization pe ratio eps dividend beta alpha",
        12: "cx nps customer satisfaction loyalty omnichannel interaction retention complaint voice feedback survey review rating comment testimonial case study success story reference referral advocacy word of mouth sentiment emotion feeling perception attitude behavior journey map touchpoint channel web mobile app store branch call center email chat social bot ivr self-service faq knowledge base community forum",
        13: "hr performance review succession career promotion workforce employee diversity hiring recruitment sourcing screening interviewing selection offer onboarding orientation training development learning coaching mentoring feedback appraisal evaluation goal objective okr compensation benefit salary bonus equity stock option perk culture engagement satisfaction morale motivation recognition reward event team group department division organization",
        14: "sox deficiency matrix testing control automation compliance dashboard reporting audit finding recommendation remediation mitigation risk assessment evaluation review policy procedure guideline standard framework regulation law act statute directive mandate requirement rule iso nist gdpr ccpa hipaa pci dss soc fedramp fisma glba sarbanes oxley anti money laundering kyc cdd edd sanctions ofac fcipa",
        15: "roadmap mvp feature backlog sprint agile scrum go-to-market lifecycle product service offering solution application app system platform module component user story epic bug defect issue incident problem change request release deployment launch iteration version update patch hotfix maintenance end of life eol sunset deprecation retirement vision strategy positioning messaging pricing packaging",
        16: "visa mastercard card payment terminal pos checkout stripe paypal transaction settlement fraud chargeback gateway network issuer acquirer processor merchant consumer wallet apple pay google pay samsung pay nfc rfid emv chip pin magnetic stripe contactless qr code barcode crypto bitcoin ethereum blockchain smart contract defi central bank digital currency cbdc stablecoin token coin",
        17: "sql select distinct insert update delete query table database row column schema etl nosql json mongodb bigquery spark pipeline data warehouse lake mart oltp olap rdbms postgresql mysql oracle sql server db2 cassandra hbase redis memcached elasticsearch solr kafka rabbitmq flume sqoop nifi airflow hadoop mapreduce hive pig impala presto athena redshift snowflake",
        18: "auth oauth saml jwt mfa sso password zero trust certificate encryption vulnerability cyber phishing threat identity access management iam idm pam rbac abac dac mac token biometrics fingerprint facial retina voice authentication authorization accountability confidentiality integrity availability cia risk hazard danger peril attack vector surface payload exploit malware virus worm trojan ransomware spyware adware botnet ddos sql injection xss csrf",
        19: "api microservices message broker middleware integration hybrid cloud architecture legacy modernization service oriented soa esb enterprise service bus event driven eda serverless faas function as a service saas paas iaas software platform infrastructure monorepo monolith distributed decentralized centralized topology pattern anti-pattern best practice design blueprint roadmap capability business information data application technology"
    }

def enrich_taxonomy(df):
    enrichment_map = get_enrichment_map()
    
    def apply_enrichment(row):
        cat_id = row['category_id']
        desc = row['processed_desc']
        if cat_id in enrichment_map:
            # Append enrichment keywords to the lexical vector
            return desc + " " + enrichment_map[cat_id]
        return desc
        
    df['enriched_desc'] = df.apply(apply_enrichment, axis=1)
    return df
