import pandas as pd
import psycopg2
from psycopg2.extras import execute_values
import sys
import re
import os

def export_to_postgres(original_filename):
    # 1. Extract date from filename (e.g., cleaned_prompts_2026-06-15.txt)
    date_match = re.search(r'(\d{4}-\d{2}-\d{2})', original_filename)
    if not date_match:
        print(f"Error: Could not extract YYYY-MM-DD date from filename '{original_filename}'")
        print("Expected format: cleaned_prompts_YYYY-MM-DD.txt")
        sys.exit(1)
        
    extracted_date = date_match.group(1)
    print(f"Extracted Date: {extracted_date}")

    # 2. Load the results generated by discovery.py
    data_path = os.path.join("data", "fully_categorized_dataset.csv")
    if not os.path.exists(data_path):
        print(f"Error: {data_path} not found. Did you run discovery.py first?")
        sys.exit(1)
        
    print("Loading categorization results...")
    df = pd.read_csv(data_path)
    
    # 3. Aggregate counts by Category and Subcategory
    print("Aggregating counts...")
    grouped = df.groupby(["category_name", "subcategory_name"]).size().reset_index(name="count")
    
    # 4. Prepare data for insertion (Date, Category, Subcategory, Count)
    records_to_insert = []
    for _, row in grouped.iterrows():
        records_to_insert.append((
            extracted_date,
            row["category_name"],
            row["subcategory_name"],
            row["count"]
        ))
        
    print(f"Prepared {len(records_to_insert)} aggregated rows for Database insertion.")

    # 5. Postgres connection parameters from environment variables
    # Modify these default values or set them as environment variables on your server
    DB_HOST = os.environ.get("DB_HOST", "localhost")
    DB_NAME = os.environ.get("DB_NAME", "postgres")
    DB_USER = os.environ.get("DB_USER", "postgres")
    DB_PASS = os.environ.get("DB_PASS", "password")
    DB_PORT = os.environ.get("DB_PORT", "5432")

    print(f"Connecting to Postgres DB '{DB_NAME}' at {DB_HOST}:{DB_PORT}...")
    
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            database=DB_NAME,
            user=DB_USER,
            password=DB_PASS,
            port=DB_PORT
        )
        cursor = conn.cursor()
        
        # Create table if it doesn't exist yet
        create_table_query = """
        CREATE TABLE IF NOT EXISTS prompt_insights (
            id SERIAL PRIMARY KEY,
            date DATE NOT NULL,
            category VARCHAR(255) NOT NULL,
            subcategory VARCHAR(255) NOT NULL,
            prompt_count INTEGER NOT NULL
        );
        """
        cursor.execute(create_table_query)
        
        # Insert the records securely using execute_values
        insert_query = """
        INSERT INTO prompt_insights (date, category, subcategory, prompt_count)
        VALUES %s
        """
        
        execute_values(cursor, insert_query, records_to_insert)
        
        conn.commit()
        print(f"Successfully inserted {len(records_to_insert)} rows into Postgres table 'prompt_insights' for Date: {extracted_date}")
        
    except Exception as e:
        print(f"Database Error: {e}")
    finally:
        if 'conn' in locals() and conn:
            cursor.close()
            conn.close()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python export_to_db.py <original_filename>")
        print("Example: python export_to_db.py cleaned_prompts_2026-06-15.txt")
        sys.exit(1)
        
    original_filename = sys.argv[1]
    export_to_postgres(original_filename)
