import pandas as pd
import re

df = pd.read_csv('data/optimized_taxonomy.csv')

# Industry Standard Mapping for the "Word Salad" Subcategories
MAPPING = {
    'Java Python C++': 'Core Programming Languages',
    'Frontend React Angular': 'Frontend Architecture',
    'Backend Node Express': 'Backend Architecture',
    'Api Rest Graphql': 'API & Integration Services',
    'Git Version Control': 'Version Control Systems',
    'Algorithm Data Structure': 'Algorithms & Data Structures',
    'Stacktrace Exception Null': 'Exception Handling & Diagnostics',
    'Memory Leak Cpu': 'Performance Profiling',
    'Application Crash Outage': 'Outage & Crash Triage',
    'Dependency Package Version': 'Package Management',
    'Sql Select Update': 'Database Querying & DML',
    'Table Column Row': 'Schema & Data Modeling',
    'Etl Pipeline Warehouse': 'Data Pipelines & Warehousing',
    'Nosql Mongodb Cassandra': 'NoSQL Database Administration',
    'Big Data (Hadoop/Spark)': 'Big Data Processing',
    'Aws Ec2 S3': 'Cloud Provisioning',
    'Kubernetes Docker Container': 'Container Orchestration',
    'Ci Cd Jenkins': 'CI/CD Automation',
    'Terraform Ansible Infrastructure': 'Infrastructure as Code (IaC)',
    'Network Load Balancer': 'Networking & Routing',
    'Authentication Oauth Saml': 'Authentication Services',
    'Authorization Rbac Role': 'Access Control & RBAC',
    'Encryption Ssl Tls': 'Cryptography & Encryption',
    'Vulnerability Malware Phishing': 'Threat Detection',
    'Compliance Gdpr Hipaa': 'Regulatory Compliance',
    'Email Draft Response': 'Email Correspondence',
    'Grammar Spelling Proofread': 'Copywriting & Proofreading',
    'Translate Language Translation': 'Translation Services',
    'Presentation Slide Deck': 'Presentation Design',
    'Documentation Manual Article': 'Technical Documentation',
    'Roi Kpi Metric': 'KPIs & Performance Metrics',
    'Revenue & Profitability': 'Revenue & Margin Tracking',
    'Roadmap Vision Mission': 'Strategic Planning',
    'Talent Hr Hiring': 'Talent Acquisition',
    'Market Competition Differentiation': 'Market Research',
    'Agile Scrum Sprint': 'Agile Methodologies',
    'Ticket Jira Issue': 'Issue Tracking',
    'Workflow Checklist Step': 'Workflow Automation',
    'Meeting Notes Agenda': 'Meeting Management',
    'Release Schedule Change': 'Release Management',
    'Unit Test Mock': 'Unit Testing',
    'Integration Test End': 'Integration Testing',
    'Regression Load Stress': 'Load & Performance Testing',
    'Qa Defect Bug': 'Quality Assurance',
    'Excel Formula Pivot': 'Spreadsheet Analytics',
    'Dashboards & Visualization': 'Dashboards & Visualization',
    'Statistics Mean Median': 'Statistical Analysis',
    'Data Cleansing Formatting': 'Data Cleansing & Transformation',
    'Python Data Science (Pandas/Numpy)': 'Data Science & Analysis',
    'Summarize Condense Abstract': 'Text Summarization',
    'Concept Ideation': 'Concept Ideation',
    'Format Structure Table': 'Document Formatting',
    'Explain Define Concept': 'Educational Explanations',
    'Math Calculate Equation': 'Mathematical Computation',
    'American Express Amex': 'Brand Representation',
    'Card Member Membership': 'Cardholder Services',
    'Merchant Global Acquiring': 'Merchant Services',
    'Amex Offers Marketing': 'Offers & Promotions',
    'Account Bank Balance': 'Account Management',
    'Application Tests': 'Application Testing',
    'Gatling Load Testing': 'Load Testing (Gatling)',
    'Regex Patterns': 'Regular Expressions',
    'Airflow Schedule Interval': 'Data Orchestration (Airflow)',
    'Uat Sit Testing': 'UAT & SIT Testing',
    'Ui Bug Screenshots': 'UI/UX Debugging',
    'Support Escalation Win': 'Support Escalations',
    'Developer Mistakes': 'Code Review Feedback',
    'It Technology Investigation': 'IT Root Cause Analysis',
    'Tableau Lod Expression': 'BI Analytics (Tableau)',
    'Google Bigquery': 'Cloud Data Warehousing (BigQuery)',
    'Power Bi Selectedvalue': 'BI Analytics (Power BI DAX)',
    'Model Id Product': 'Product Data Modeling',
    'Xml Central Configuration': 'XML Configuration Management',
    'Pib Predictive Models': 'Predictive Modeling',
    'Refactoring Lpad': 'Code Refactoring',
    'Correlation Analysis': 'Correlation & Bivariate Analysis',
    'Incident Alert Monitoring': 'Incident Monitoring',
    'Laptop Windows Hardware': 'Hardware & IT Support',
    'Python Pypi Packages': 'Python Dependency Management',
    'Cron Job Scheduling': 'Job Scheduling',
    'Systems Cutover Deployments': 'System Cutover & Deployments',
    'Config Tag Settings': 'Configuration Management',
    'Rfc Request For': 'RFC & Change Management',
    'Splunk Total Rows': 'Log Analytics (Splunk)',
    'Shell Script Parameters': 'Shell Scripting',
    'Kernel Application Pcn': 'Kernel & System Ops',
    'Backup Nat Gateway': 'Disaster Recovery & Networking',
    'Risk Control Policies': 'Risk & Control Governance',
    'Privacy Data Pii': 'Data Privacy (PII)',
    'Regulatory Requirements Regulation': 'Regulatory Operations',
    'On-Call Pager Incident': 'On-Call Operations',
    'Falcon Gmas Security': 'Fraud & Security Ops',
    'Cyberark Secrets Vault': 'Secrets Management (CyberArk)',
    'Entra Id Seasonality': 'Identity Management (Entra)',
    'Write Email Team': 'Internal Team Comms',
    'Slack Message Communication': 'Instant Messaging Ops',
    'Attrition Retention Employee': 'Employee Retention',
    'Vendor Management Third': 'Vendor & Third-Party Mgmt',
    'Hr Payroll Salary': 'Payroll Operations',
    'Group Training Workshops': 'Training & Workshops',
    'Live Chat Concurrency': 'Live Chat Operations',
    'Ownership Accountability Culture': 'Organizational Culture',
    'Capacity Shift Planning': 'Capacity Planning',
    'Shareholder Trends (TSR)': 'Investor Relations',
    'International Pricing Models': 'International Pricing Strategy',
    'Sales Deal Closing': 'Sales & Deal Management',
    'Data Governance Delivery': 'Data Governance',
    'Product Manager Management': 'Product Management',
    'Intake Form Process': 'Intake & Triage',
    'Debugging & Error Logs': 'Debugging & Log Analysis',
    'Code Review & Changes': 'Code Review',
    'Pass Fail Test': 'Test Execution',
    'Test Expected Actual': 'Test Assertions',
    'Data Reporting Report': 'Data Reporting',
    'Ai Embedding Similarity': 'AI/ML Vector Operations',
    'Sharepoint Sla Slas': 'SLA Management',
    'Documentation Technical Docs': 'Technical Documentation',
    'Pop Operations Center': 'NOC / Operations Center',
    'Workflow Approvals Sorting': 'Approval Workflows',
    'Openai Customgpt': 'LLM Integration (OpenAI)',
    'Knowledge Base & Jump Guides': 'Knowledge Management',
    'Supplier Buyer Network': 'Supplier Networks',
    'Transaction Fraud Chargeback': 'Fraud & Chargebacks',
    'Pricing Ctl Settings': 'Pricing Configuration',
    'Direct Pay Deposit': 'Payment & Deposit Ops',
    'Treasury Funding Liquidity': 'Treasury & Liquidity',
    'External Loan Financing': 'External Financing',
    'Employee Awards & Recognition': 'Employee Recognition',
    'Targeting Eligibility': 'Marketing Targeting',
    'Process Automation Rpa': 'RPA & Automation',
    'Hr Immigration Manager': 'HR Immigration Services',
    'Benefits Enrollment Lift': 'Benefits Enrollment',
    'Hr Benefits Eligibility': 'Benefits Administration',
    'Hr Interviewer Recruiter': 'Recruiting Operations',
    'Singapore Communications': 'Regional Comms (Singapore)',
    'Wfm Coordination': 'Workforce Management (WFM)',
    'Accounting Journal Entries': 'Accounting & Journaling',
    'Pcm Rule Allocation': 'Rule Allocation (PCM)',
    'Ebitda Financial Metrics': 'Financial Metrics (EBITDA)',
    'Pricing Approvals': 'Pricing Approvals',
    'End of Day (EOD) Operations': 'EOD Operations',
    'Capital Timing Finance': 'Capital Planning',
    'Financials Fin Reporting': 'Financial Reporting',
    'Emburse Expense Management': 'Expense Management',
    'Pricing Study Research': 'Pricing Research',
    'Asset Management Entry': 'Asset Management',
    'Bank Locations': 'Branch Operations',
    'Legal & Tribunal Proceedings': 'Legal Proceedings',
    'Finance Actuals Adb': 'Financial Actuals',
    'Treasury Report Script': 'Treasury Reporting',
    'Finance Annual Spend': 'Annual Spend Analysis'
}

def clean_name(name):
    if name in MAPPING:
        return MAPPING[name]
    
    # Fallback for anything not mapped: Clean up trailing word salad
    name = re.sub(r'\s+(And|Or|For|To|Of|The|In|On)\s*$', '', name, flags=re.IGNORECASE)
    return name.title()

df['subcategory_name'] = df['subcategory_name'].apply(clean_name)
df.to_csv('data/optimized_taxonomy.csv', index=False)
print("Successfully renamed subcategories to industry standards.")
